-- SCHOLARSHIP TRACKING SYSTEM - FINAL REBUILD SCHEMA
-- Supabase / PostgreSQL
-- WARNING: This migration drops and recreates scholarship-system tables.

begin;

create extension if not exists "pgcrypto";

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.set_updated_at() cascade;

drop table if exists public.audit_logs cascade;
drop table if exists public.notifications cascade;
drop table if exists public.disbursements cascade;
drop table if exists public.application_results cascade;
drop table if exists public.evaluations cascade;
drop table if exists public.review_assignments cascade;
drop table if exists public.documents cascade;
drop table if exists public.application_status_history cascade;
drop table if exists public.applications cascade;
drop table if exists public.document_requirements cascade;
drop table if exists public.criteria cascade;
drop table if exists public.scholarships cascade;
drop table if exists public.statuses cascade;
drop table if exists public.accounting_staff cascade;
drop table if exists public.document_reviewers cascade;
drop table if exists public.committee_members cascade;
drop table if exists public.scholarship_officers cascade;
drop table if exists public.staff_profiles cascade;
drop table if exists public.student_profiles cascade;
drop table if exists public.role_permissions cascade;
drop table if exists public.user_roles cascade;
drop table if exists public.permissions cascade;
drop table if exists public.roles cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  first_name text,
  last_name text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.student_profiles (
  student_id uuid primary key references public.profiles(id) on delete cascade,
  student_code text unique not null,
  faculty text,
  major text,
  year_level integer,
  gpa numeric(3,2),
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (year_level is null or year_level between 1 and 8),
  check (gpa is null or gpa between 0 and 4)
);

create table public.staff_profiles (
  staff_id uuid primary key references public.profiles(id) on delete cascade,
  staff_code text unique,
  department text,
  position text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles (
  role_id bigint generated by default as identity primary key,
  role_name text unique not null,
  description text,
  created_at timestamptz not null default now()
);

create table public.permissions (
  permission_id bigint generated by default as identity primary key,
  permission_name text unique not null,
  description text,
  created_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.roles(role_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table public.role_permissions (
  role_id bigint not null references public.roles(role_id) on delete cascade,
  permission_id bigint not null references public.permissions(permission_id) on delete cascade,
  primary key (role_id, permission_id)
);

create table public.scholarship_officers (
  staff_id uuid primary key references public.staff_profiles(staff_id) on delete cascade
);
create table public.committee_members (
  staff_id uuid primary key references public.staff_profiles(staff_id) on delete cascade
);
create table public.document_reviewers (
  staff_id uuid primary key references public.staff_profiles(staff_id) on delete cascade
);
create table public.accounting_staff (
  staff_id uuid primary key references public.staff_profiles(staff_id) on delete cascade
);

create table public.scholarships (
  scholarship_id bigint generated by default as identity primary key,
  scholarship_name text not null,
  description text,
  provider text,
  amount numeric(12,2),
  max_recipients integer,
  application_start date,
  application_end date,
  status text not null default 'draft',
  created_by uuid references public.scholarship_officers(staff_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount is null or amount >= 0),
  check (max_recipients is null or max_recipients > 0),
  check (application_end is null or application_start is null or application_end >= application_start)
);

create table public.criteria (
  criterion_id bigint generated by default as identity primary key,
  scholarship_id bigint not null references public.scholarships(scholarship_id) on delete cascade,
  criterion_name text not null,
  description text,
  criterion_type text,
  min_value numeric,
  max_value numeric,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  check (max_value is null or min_value is null or max_value >= min_value)
);

create table public.document_requirements (
  requirement_id bigint generated by default as identity primary key,
  scholarship_id bigint not null references public.scholarships(scholarship_id) on delete cascade,
  document_name text not null,
  description text,
  is_required boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.applications (
  application_id bigint generated by default as identity primary key,
  student_id uuid not null references public.student_profiles(student_id) on delete cascade,
  scholarship_id bigint not null references public.scholarships(scholarship_id) on delete cascade,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, scholarship_id)
);

create table public.statuses (
  status_id bigint generated by default as identity primary key,
  status_type text not null,
  status_code text not null,
  status_name text not null,
  description text,
  created_at timestamptz not null default now(),
  unique(status_type, status_code)
);

create table public.application_status_history (
  history_id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(application_id) on delete cascade,
  status_id bigint not null references public.statuses(status_id),
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now(),
  remark text
);

create table public.documents (
  document_id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(application_id) on delete cascade,
  requirement_id bigint references public.document_requirements(requirement_id) on delete set null,
  file_name text not null,
  file_path text not null,
  file_type text,
  file_size bigint,
  verification_status text not null default 'pending',
  verified_by uuid references public.document_reviewers(staff_id) on delete set null,
  verified_at timestamptz,
  verification_remark text,
  uploaded_at timestamptz not null default now()
);

create table public.review_assignments (
  assignment_id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(application_id) on delete cascade,
  committee_id uuid not null references public.committee_members(staff_id) on delete cascade,
  assigned_by uuid references public.scholarship_officers(staff_id) on delete set null,
  assigned_at timestamptz not null default now(),
  status text not null default 'assigned',
  unique(application_id, committee_id)
);

create table public.evaluations (
  evaluation_id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.review_assignments(assignment_id) on delete cascade,
  score numeric(5,2),
  recommendation text,
  comment text,
  evaluated_at timestamptz,
  created_at timestamptz not null default now(),
  unique(assignment_id),
  check (score is null or score >= 0)
);

create table public.application_results (
  result_id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(application_id) on delete cascade,
  result text not null,
  rank integer,
  announced_at timestamptz,
  announced_by uuid references public.scholarship_officers(staff_id) on delete set null,
  remark text,
  unique(application_id),
  check (rank is null or rank > 0)
);

create table public.disbursements (
  disbursement_id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(application_id) on delete cascade,
  amount numeric(12,2) not null,
  status text not null default 'pending',
  transfer_date date,
  transfer_reference text,
  processed_by uuid references public.accounting_staff(staff_id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  unique(application_id),
  check (amount >= 0)
);

create table public.notifications (
  notification_id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  notification_type text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.audit_logs (
  audit_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  table_name text,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index idx_scholarships_status on public.scholarships(status);
create index idx_criteria_scholarship on public.criteria(scholarship_id);
create index idx_document_requirements_scholarship on public.document_requirements(scholarship_id);
create index idx_applications_student on public.applications(student_id);
create index idx_applications_scholarship on public.applications(scholarship_id);
create index idx_application_status_history_application on public.application_status_history(application_id);
create index idx_documents_application on public.documents(application_id);
create index idx_review_assignments_application on public.review_assignments(application_id);
create index idx_review_assignments_committee on public.review_assignments(committee_id);
create index idx_notifications_user on public.notifications(user_id);
create index idx_audit_logs_user on public.audit_logs(user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = public
as $$ begin new.updated_at = now(); return new; end; $$;

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger student_profiles_updated_at before update on public.student_profiles for each row execute function public.set_updated_at();
create trigger staff_profiles_updated_at before update on public.staff_profiles for each row execute function public.set_updated_at();
create trigger scholarships_updated_at before update on public.scholarships for each row execute function public.set_updated_at();
create trigger applications_updated_at before update on public.applications for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles(id,email,first_name,last_name)
  values(new.id,new.email,new.raw_user_meta_data ->> 'first_name',new.raw_user_meta_data ->> 'last_name')
  on conflict (id) do nothing;
  return new;
end; $$;

create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.roles(role_name,description) values
('student','นักศึกษา'),('scholarship_officer','เจ้าหน้าที่ทุนการศึกษา'),
('committee','กรรมการพิจารณาทุน'),('document_reviewer','ผู้ตรวจสอบเอกสาร'),
('accounting_staff','เจ้าหน้าที่การเงิน'),('admin','ผู้ดูแลระบบ')
on conflict (role_name) do nothing;

insert into public.statuses(status_type,status_code,status_name,description) values
('application','draft','ร่างใบสมัคร','นักศึกษายังไม่ได้ส่งใบสมัคร'),
('application','submitted','ส่งใบสมัครแล้ว','นักศึกษาส่งใบสมัครเรียบร้อย'),
('application','document_review','ตรวจสอบเอกสาร','เจ้าหน้าที่กำลังตรวจสอบเอกสาร'),
('application','need_revision','ต้องแก้ไขเอกสาร','เอกสารต้องได้รับการแก้ไขหรือส่งใหม่'),
('application','qualification_review','ตรวจสอบคุณสมบัติ','เจ้าหน้าที่กำลังตรวจสอบคุณสมบัติ'),
('application','committee_review','กรรมการพิจารณา','กรรมการกำลังประเมินใบสมัคร'),
('application','approved','ผ่านการพิจารณา','ได้รับทุน'),
('application','rejected','ไม่ผ่านการพิจารณา','ไม่ได้รับทุน'),
('application','completed','เสร็จสิ้น','กระบวนการสมัครเสร็จสมบูรณ์'),
('scholarship','draft','แบบร่าง','ยังไม่เผยแพร่'),
('scholarship','published','เผยแพร่แล้ว','เผยแพร่ข้อมูลทุนแล้ว'),
('scholarship','open','เปิดรับสมัคร','สามารถสมัครทุนได้'),
('scholarship','closed','ปิดรับสมัคร','ไม่สามารถสมัครทุนได้'),
('scholarship','completed','สิ้นสุด','ทุนสิ้นสุดกระบวนการ')
on conflict (status_type,status_code) do nothing;

alter table public.profiles enable row level security;
alter table public.student_profiles enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.scholarship_officers enable row level security;
alter table public.committee_members enable row level security;
alter table public.document_reviewers enable row level security;
alter table public.accounting_staff enable row level security;
alter table public.scholarships enable row level security;
alter table public.criteria enable row level security;
alter table public.document_requirements enable row level security;
alter table public.applications enable row level security;
alter table public.statuses enable row level security;
alter table public.application_status_history enable row level security;
alter table public.documents enable row level security;
alter table public.review_assignments enable row level security;
alter table public.evaluations enable row level security;
alter table public.application_results enable row level security;
alter table public.disbursements enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_select_own on public.profiles for select to authenticated using(id=auth.uid());
create policy profiles_update_own on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy student_profiles_select_own on public.student_profiles for select to authenticated using(student_id=auth.uid());
create policy student_profiles_insert_own on public.student_profiles for insert to authenticated with check(student_id=auth.uid());
create policy student_profiles_update_own on public.student_profiles for update to authenticated using(student_id=auth.uid()) with check(student_id=auth.uid());
create policy staff_profiles_select_own on public.staff_profiles for select to authenticated using(staff_id=auth.uid());
create policy staff_profiles_update_own on public.staff_profiles for update to authenticated using(staff_id=auth.uid()) with check(staff_id=auth.uid());
create policy roles_authenticated_read on public.roles for select to authenticated using(true);
create policy permissions_authenticated_read on public.permissions for select to authenticated using(true);
create policy user_roles_own_read on public.user_roles for select to authenticated using(user_id=auth.uid());
create policy role_permissions_authenticated_read on public.role_permissions for select to authenticated using(true);
create policy scholarships_public_read on public.scholarships for select to anon,authenticated using(status in ('published','open'));
create policy criteria_public_read on public.criteria for select to anon,authenticated using(exists(select 1 from public.scholarships s where s.scholarship_id=criteria.scholarship_id and s.status in ('published','open')));
create policy document_requirements_public_read on public.document_requirements for select to anon,authenticated using(exists(select 1 from public.scholarships s where s.scholarship_id=document_requirements.scholarship_id and s.status in ('published','open')));
create policy applications_student_read on public.applications for select to authenticated using(student_id=auth.uid());
create policy applications_student_insert on public.applications for insert to authenticated with check(student_id=auth.uid());
create policy applications_student_update on public.applications for update to authenticated using(student_id=auth.uid()) with check(student_id=auth.uid());
create policy statuses_authenticated_read on public.statuses for select to authenticated using(true);
create policy statuses_public_read on public.statuses for select to anon using(status_type='scholarship');
create policy application_status_history_student_read on public.application_status_history for select to authenticated using(exists(select 1 from public.applications a where a.application_id=application_status_history.application_id and a.student_id=auth.uid()));
create policy documents_student_read on public.documents for select to authenticated using(exists(select 1 from public.applications a where a.application_id=documents.application_id and a.student_id=auth.uid()));
create policy documents_student_insert on public.documents for insert to authenticated with check(exists(select 1 from public.applications a where a.application_id=documents.application_id and a.student_id=auth.uid()));
create policy documents_student_update on public.documents for update to authenticated using(exists(select 1 from public.applications a where a.application_id=documents.application_id and a.student_id=auth.uid())) with check(exists(select 1 from public.applications a where a.application_id=documents.application_id and a.student_id=auth.uid()));
create policy review_assignments_committee_read on public.review_assignments for select to authenticated using(committee_id=auth.uid());
create policy evaluations_committee_read on public.evaluations for select to authenticated using(exists(select 1 from public.review_assignments ra where ra.assignment_id=evaluations.assignment_id and ra.committee_id=auth.uid()));
create policy evaluations_committee_insert on public.evaluations for insert to authenticated with check(exists(select 1 from public.review_assignments ra where ra.assignment_id=evaluations.assignment_id and ra.committee_id=auth.uid()));
create policy evaluations_committee_update on public.evaluations for update to authenticated using(exists(select 1 from public.review_assignments ra where ra.assignment_id=evaluations.assignment_id and ra.committee_id=auth.uid())) with check(exists(select 1 from public.review_assignments ra where ra.assignment_id=evaluations.assignment_id and ra.committee_id=auth.uid()));
create policy application_results_student_read on public.application_results for select to authenticated using(exists(select 1 from public.applications a where a.application_id=application_results.application_id and a.student_id=auth.uid()));
create policy application_results_committee_read on public.application_results for select to authenticated using(exists(select 1 from public.review_assignments ra join public.evaluations e on e.assignment_id=ra.assignment_id where ra.application_id=application_results.application_id and ra.committee_id=auth.uid()));
create policy disbursements_student_read on public.disbursements for select to authenticated using(exists(select 1 from public.applications a where a.application_id=disbursements.application_id and a.student_id=auth.uid()));
create policy notifications_own_read on public.notifications for select to authenticated using(user_id=auth.uid());
create policy notifications_own_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

revoke execute on function public.handle_new_user() from public,anon,authenticated;
revoke execute on function public.set_updated_at() from public,anon,authenticated;

commit;
